/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostelmanagement;

/**
 *
 * @author SAM
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hostelbutton = new javax.swing.JButton();
        studentbutton = new javax.swing.JButton();
        roombutton = new javax.swing.JButton();
        feesbutton = new javax.swing.JButton();
        messbutton = new javax.swing.JButton();
        messempbutton = new javax.swing.JButton();
        visitorbutton = new javax.swing.JButton();
        exitwelcomebutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Welcome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 36), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Hostel Management System");

        hostelbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hostelbutton.setText("Hostel Details");
        hostelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostelbuttonActionPerformed(evt);
            }
        });

        studentbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        studentbutton.setText("Student Details");
        studentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentbuttonActionPerformed(evt);
            }
        });

        roombutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        roombutton.setText("Room Details");
        roombutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roombuttonActionPerformed(evt);
            }
        });

        feesbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        feesbutton.setText("Fees Details");
        feesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feesbuttonActionPerformed(evt);
            }
        });

        messbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        messbutton.setText("Mess Details");
        messbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messbuttonActionPerformed(evt);
            }
        });

        messempbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        messempbutton.setText("Mess Employee Details");
        messempbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messempbuttonActionPerformed(evt);
            }
        });

        visitorbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        visitorbutton.setText("Visitor Details");
        visitorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorbuttonActionPerformed(evt);
            }
        });

        exitwelcomebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitwelcomebutton.setForeground(new java.awt.Color(255, 0, 0));
        exitwelcomebutton.setText("EXIT APPLICATION");
        exitwelcomebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitwelcomebuttonActionPerformed(evt);
            }
        });

        jPanel2.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/sxc.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(-6, -6, 770, 350);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitwelcomebutton)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(feesbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(messbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hostelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                    .addComponent(roombutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(studentbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(messempbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(visitorbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostelbutton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(roombutton)
                                .addGap(18, 18, 18)
                                .addComponent(studentbutton)
                                .addGap(18, 18, 18)
                                .addComponent(feesbutton)
                                .addGap(18, 18, 18)
                                .addComponent(messbutton)
                                .addGap(18, 18, 18)
                                .addComponent(messempbutton)
                                .addGap(18, 18, 18)
                                .addComponent(visitorbutton)
                                .addGap(18, 18, 18)
                                .addComponent(exitwelcomebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitwelcomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitwelcomebuttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitwelcomebuttonActionPerformed

    private void hostelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostelbuttonActionPerformed
        // TODO add your handling code here:
        HostelFrame hd;
            hd = new HostelFrame();
            hd.setVisible(true);
    }//GEN-LAST:event_hostelbuttonActionPerformed

    private void studentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentbuttonActionPerformed
        // TODO add your handling code here:
        studentdetails sd=new studentdetails();
        sd.setVisible(true);
    }//GEN-LAST:event_studentbuttonActionPerformed

    private void roombuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roombuttonActionPerformed
        // TODO add your handling code here:
         roomdetails rd=new roomdetails();
        rd.setVisible(true);
    }//GEN-LAST:event_roombuttonActionPerformed

    private void feesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feesbuttonActionPerformed
        // TODO add your handling code here:
        fessdetails fd=new fessdetails();
        fd.setVisible(true);
    }//GEN-LAST:event_feesbuttonActionPerformed

    private void messbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messbuttonActionPerformed
        // TODO add your handling code here:
        messdetails md=new messdetails();
        md.setVisible(true);
    }//GEN-LAST:event_messbuttonActionPerformed

    private void messempbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messempbuttonActionPerformed
        // TODO add your handling code here:
        messempdetail med=new messempdetail();
        med.setVisible(true);
    }//GEN-LAST:event_messempbuttonActionPerformed

    private void visitorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorbuttonActionPerformed
        // TODO add your handling code here:
        visitordetails med=new visitordetails();
        med.setVisible(true);
    }//GEN-LAST:event_visitorbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitwelcomebutton;
    private javax.swing.JButton feesbutton;
    private javax.swing.JButton hostelbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton messbutton;
    private javax.swing.JButton messempbutton;
    private javax.swing.JButton roombutton;
    private javax.swing.JButton studentbutton;
    private javax.swing.JButton visitorbutton;
    // End of variables declaration//GEN-END:variables
}
